version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - task-management

  db:
    image: mysql:8.0
    container_name: task-management-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"  # Ubah dari 3306:3306 ke 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - task-management

  nginx:
    image: nginx:alpine
    container_name: task-management-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - task-management

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task-management-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - task-management

networks:
  task-management:
    driver: bridge

volumes:
  dbdata: